# Generated by Django 3.0.14 on 2022-02-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [        
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Frames', 'Frames'), ('Contact Lens', 'Contact Lens'), ('Solutions', 'Solutions'), ('Sunglass', 'Sunglass'), ('Complete Eyeglass', 'Complete Eyeglass')], max_length=25, null=True),
        ),        
    ]
